#!/usr/bin/env python3
"""InfoNCE contrastive loss for (reaction, catalyst-complex) pairs.

Given:
  h_r: (B, D) reaction embeddings
  h_m: (B, D) catalyst-complex embeddings (positive for each reaction)
  optionally: (B, K, D) hard-negative complex embeddings

The standard InfoNCE loss uses in-batch other examples as negatives. We
extend with explicit hard negatives generated by:
  - same substrate / wrong metal
  - same metal / wrong ligand
  - same ligand / wrong oxidation state
  - same metal+ligand / wrong mechanism

Auxiliary heads (predicting metal family, ligand class, mechanism) can be
attached for multi-task pretraining.
"""
from __future__ import annotations
import torch
import torch.nn as nn
import torch.nn.functional as F


def info_nce_loss(h_r: torch.Tensor, h_m: torch.Tensor, *,
                  temperature: float = 0.1,
                  hard_negatives: torch.Tensor = None) -> torch.Tensor:
    """
    Symmetric InfoNCE (CLIP-style).
      L = 0.5 * (CE(reaction_to_catalyst) + CE(catalyst_to_reaction))

    Args:
      h_r: (B, D) reaction embeddings (assumed L2-normalized)
      h_m: (B, D) positive catalyst embeddings
      temperature: softmax temperature; lower = sharper
      hard_negatives: optional (B, K, D) extra negatives per anchor

    Returns:
      scalar loss
    """
    B, D = h_r.shape
    # Cosine similarity matrix (B, B)
    logits = (h_r @ h_m.t()) / temperature

    if hard_negatives is not None:
        # (B, K, D) -> add as additional columns: (B, B + B*K)
        # Each anchor sees its own K hard negatives appended
        # extra[b] = h_r[b] @ hard_negatives[b].T -> (K,)
        extra = torch.einsum("bd,bkd->bk", h_r, hard_negatives) / temperature
        logits = torch.cat([logits, extra], dim=1)   # (B, B+K)

    targets = torch.arange(B, device=h_r.device)
    loss_r_to_m = F.cross_entropy(logits, targets)

    # Reverse direction (only the BxB part; hard negatives are anchor-specific)
    logits_rev = (h_m @ h_r.t()) / temperature
    loss_m_to_r = F.cross_entropy(logits_rev, targets)

    return 0.5 * (loss_r_to_m + loss_m_to_r)


def retrieval_metrics(h_r: torch.Tensor, h_m: torch.Tensor, top_ks=(1, 5, 10)):
    """Compute top-k retrieval accuracy on a held-out batch.

    For each reaction r_i, rank all complexes m_j by cosine similarity.
    Hits@k = fraction of reactions where the correct catalyst is in the top-k.
    """
    B = h_r.size(0)
    sim = h_r @ h_m.t()                        # (B, B)
    ranks = sim.argsort(dim=-1, descending=True)
    targets = torch.arange(B, device=h_r.device)
    out = {}
    for k in top_ks:
        hit = (ranks[:, :k] == targets.unsqueeze(-1)).any(dim=-1).float().mean()
        out[f"hits@{k}"] = hit.item()
    # Mean rank
    pos = (ranks == targets.unsqueeze(-1)).nonzero(as_tuple=False)[:, 1].float()
    out["mean_rank"] = pos.mean().item()
    out["mrr"] = (1.0 / (pos + 1)).mean().item()
    return out


class ProjectionHead(nn.Module):
    """Two-layer projection head + L2 normalize for contrastive learning.
    Following SimCLR / CLIP best practice: projecting is critical for transfer."""

    def __init__(self, in_dim: int, out_dim: int, hidden_dim: int = None):
        super().__init__()
        hidden_dim = hidden_dim or in_dim
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, out_dim),
        )

    def forward(self, x):
        z = self.net(x)
        return F.normalize(z, dim=-1)
